permalink: /:title/
exclude: ["README.md", "bin", "appengine", "old_blogspot", ".gitignore", "Rakefile"]
production_url : http://armoucar.me

pygments: true

title: armoucar.me
author:
   name: Arthur Carvalho
