permalink: /:title/
exclude: ["README.md", "bin", "appengine", "old_blogspot", ".gitignore", "Rakefile", "new"]
production_url : http://armoucar.me

name: Arthur Carvalho
url: http://arthurcarvalho.com/

pygments: true

title: armoucar.me
author:
   name: Arthur Carvalho
